create extension if not exists pgcrypto;

create type public.app_role as enum ('ATTENDEE','ARTIST','ORGANIZER','VENUE_MANAGER','EVENT_STAFF','ADMIN','SUPER_ADMIN');
create type public.event_status as enum ('DRAFT','PENDING_REVIEW','CHANGES_REQUESTED','APPROVED','PUBLISHED','SOLD_OUT','LIVE','COMPLETED','CANCELLED','REJECTED');
create type public.reservation_status as enum ('ACTIVE','EXPIRED','CANCELLED','CONVERTED');
create type public.order_status as enum ('CART','RESERVED','PENDING_PAYMENT','PAID','FULFILLED','PAYMENT_FAILED','CANCELLED','EXPIRED','REFUNDED','PARTIALLY_REFUNDED');
create type public.payment_status as enum ('INITIALIZED','PROVIDER_PENDING','VERIFIED_SUCCESS','FAILED','EXPIRED','REFUNDED');
create type public.ticket_status as enum ('ISSUED','ACTIVE','CHECKED_IN','CANCELLED','REFUNDED','EXPIRED');
create type public.booking_status as enum ('DRAFT','SUBMITTED','REVIEWING','NEGOTIATING','ACCEPTED','REJECTED','CANCELLED','CONFIRMED','COMPLETED');

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_url text,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  code public.app_role unique not null,
  label text not null
);

create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  code text unique not null,
  label text not null
);

create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  slug text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.venues (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  city text not null,
  address text,
  capacity integer check (capacity is null or capacity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.artists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  bio text,
  verified boolean not null default false,
  follower_count integer not null default 0 check (follower_count >= 0),
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid references auth.users(id) on delete set null,
  venue_id uuid references public.venues(id) on delete set null,
  title text not null,
  description text,
  event_type text,
  city text not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  cover_url text,
  status public.event_status not null default 'DRAFT',
  rating numeric(3,2) check (rating is null or (rating >= 0 and rating <= 5)),
  review_count integer not null default 0 check (review_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_categories (
  event_id uuid not null references public.events(id) on delete cascade,
  category_id uuid not null references public.categories(id) on delete cascade,
  primary key (event_id, category_id)
);

create table if not exists public.event_artists (
  event_id uuid not null references public.events(id) on delete cascade,
  artist_id uuid not null references public.artists(id) on delete cascade,
  primary key (event_id, artist_id)
);

create table if not exists public.ticket_types (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  name text not null,
  price numeric(12,2) not null check (price >= 0),
  capacity integer not null check (capacity > 0),
  sold integer not null default 0 check (sold >= 0),
  reserved integer not null default 0 check (reserved >= 0),
  sales_start timestamptz,
  sales_end timestamptz,
  maximum_per_customer integer not null default 4 check (maximum_per_customer > 0),
  created_at timestamptz not null default now(),
  check (sold + reserved <= capacity)
);

create table if not exists public.ticket_reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  status public.reservation_status not null default 'ACTIVE',
  expires_at timestamptz not null,
  idempotency_key text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.reservation_items (
  reservation_id uuid not null references public.ticket_reservations(id) on delete cascade,
  ticket_type_id uuid not null references public.ticket_types(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  primary key (reservation_id, ticket_type_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  reservation_id uuid references public.ticket_reservations(id) on delete set null,
  status public.order_status not null default 'CART',
  currency text not null default 'NGN',
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  service_fee numeric(12,2) not null default 0 check (service_fee >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  ticket_type_id uuid not null references public.ticket_types(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0)
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  provider text not null,
  provider_reference text,
  idempotency_key text unique not null,
  status public.payment_status not null default 'INITIALIZED',
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'NGN',
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  ticket_type_id uuid not null references public.ticket_types(id) on delete restrict,
  owner_id uuid not null references auth.users(id) on delete restrict,
  qr_token_hash text unique not null,
  status public.ticket_status not null default 'ISSUED',
  checked_in_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.artist_followers (
  artist_id uuid not null references public.artists(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (artist_id, user_id)
);

create table if not exists public.event_favorites (
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create table if not exists public.songs (
  id uuid primary key default gen_random_uuid(),
  artist_id uuid references public.artists(id) on delete set null,
  title text not null,
  duration_seconds integer not null check (duration_seconds > 0),
  audio_url text,
  cover_url text,
  play_count bigint not null default 0 check (play_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.playlist_items (
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  song_id uuid not null references public.songs(id) on delete cascade,
  position integer not null default 0,
  primary key (playlist_id, song_id)
);

create table if not exists public.music_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id uuid not null references public.songs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, song_id)
);

create table if not exists public.play_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id uuid not null references public.songs(id) on delete cascade,
  played_at timestamptz not null default now(),
  seconds_played integer not null default 0 check (seconds_played >= 0)
);

create table if not exists public.artist_booking_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references auth.users(id) on delete restrict,
  artist_id uuid not null references public.artists(id) on delete restrict,
  event_name text not null,
  event_type text not null,
  event_date date not null,
  expected_audience integer not null check (expected_audience > 0),
  budget numeric(12,2) not null check (budget >= 0),
  message text not null,
  status public.booking_status not null default 'SUBMITTED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists events_public_search_idx on public.events using gin (to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(city,'')));
create index if not exists artists_search_idx on public.artists using gin (to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(bio,'')));
create index if not exists songs_search_idx on public.songs using gin (to_tsvector('simple', coalesce(title,'')));
create index if not exists events_status_starts_idx on public.events(status, starts_at);
create index if not exists ticket_types_event_idx on public.ticket_types(event_id);
create index if not exists reservations_expiry_idx on public.ticket_reservations(status, expires_at);

insert into public.roles (code, label) values
  ('ATTENDEE','Attendee'),('ARTIST','Artist'),('ORGANIZER','Organizer'),('VENUE_MANAGER','Venue manager'),('EVENT_STAFF','Event staff'),('ADMIN','Admin'),('SUPER_ADMIN','Super admin')
on conflict (code) do nothing;

insert into public.permissions (code, label) values
  ('events.view','View published events'),('events.create','Create events'),('events.update','Update owned events'),('events.submit','Submit events for review'),('events.publish','Publish approved events'),('events.moderate','Moderate events'),('tickets.create','Create ticket types'),('tickets.manage','Manage ticket inventory'),('tickets.scan','Scan assigned tickets'),('orders.create','Create orders'),('orders.view_own','View own orders'),('orders.view_owned','View owned-event orders'),('orders.refund','Manage refunds'),('artists.manage','Manage artist profile'),('artists.verify','Verify artists'),('venues.manage','Manage venues'),('users.manage','Manage users'),('payments.view','View payments'),('payments.refund','Refund payments'),('reports.view','View reports'),('audit.view','View audit logs'),('roles.manage','Manage roles'),('bookings.create','Create bookings'),('bookings.review_assigned','Review assigned bookings'),('music.manage_own','Manage own music library')
on conflict (code) do nothing;

alter table public.user_profiles enable row level security;
alter table public.events enable row level security;
alter table public.artists enable row level security;
alter table public.venues enable row level security;
alter table public.categories enable row level security;
alter table public.songs enable row level security;
alter table public.event_favorites enable row level security;
alter table public.artist_followers enable row level security;
alter table public.tickets enable row level security;
alter table public.orders enable row level security;
alter table public.artist_booking_requests enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_items enable row level security;
alter table public.music_favorites enable row level security;
alter table public.play_history enable row level security;

create policy "public can view published events" on public.events for select using (status in ('PUBLISHED','SOLD_OUT','LIVE','COMPLETED'));
create policy "public can view artists" on public.artists for select using (true);
create policy "public can view venues" on public.venues for select using (true);
create policy "public can view categories" on public.categories for select using (true);
create policy "public can view songs" on public.songs for select using (true);
create policy "users manage own profile" on public.user_profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "users manage own favorites" on public.event_favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own follows" on public.artist_followers for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users view own tickets" on public.tickets for select using (auth.uid() = owner_id);
create policy "users view own orders" on public.orders for select using (auth.uid() = user_id);
create policy "users create bookings" on public.artist_booking_requests for insert with check (auth.uid() = requester_id);
create policy "users view own bookings" on public.artist_booking_requests for select using (auth.uid() = requester_id);
create policy "users manage own playlists" on public.playlists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own playlist items" on public.playlist_items for all using (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid())) with check (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid()));
create policy "users manage own music favorites" on public.music_favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own history" on public.play_history for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
