import { useMemo, useState } from "react";

const GROUPS = [
  { id: "overview", label: "Overview", items: [{ id: "overview", label: "Overview" }] },
  { id: "people", label: "People", items: [
    { id: "users", label: "All Users" }, { id: "artists", label: "Artists", role: "ARTIST" }, { id: "organizers", label: "Event Organizers", role: "ORGANIZER" }, { id: "venues", label: "Venue Managers", role: "VENUE_MANAGER" }, { id: "staff", label: "Event Staff", role: "EVENT_STAFF" }, { id: "admins", label: "Admins", role: "ADMIN" }, { id: "super_admins", label: "Super Admins", role: "SUPER_ADMIN" }, { id: "attendees", label: "Attendees", role: "ATTENDEE" }, { id: "other_roles", label: "Other Roles", role: "OTHER" }, { id: "blocked_users", label: "Blocked Users", role: "BLOCKED" },
  ] },
  { id: "verification", label: "Verification", items: [
    { id: "applications", label: "Pending Applications" }, { id: "verification", label: "All Verification" }, { id: "verification_artists", label: "Artists" }, { id: "verification_organizers", label: "Event Organizers" }, { id: "verification_venues", label: "Venue Managers" }, { id: "verification_approved", label: "Approved" }, { id: "verification_rejected", label: "Rejected" }, { id: "verification_settings", label: "Verification Settings" },
  ] },
  { id: "content", label: "Content", items: [
    { id: "content_artists", label: "Artists" }, { id: "content_music", label: "Music" }, { id: "content_albums", label: "Albums" }, { id: "content_videos", label: "Music Videos" }, { id: "content_venues", label: "Venues" }, { id: "content_organizers", label: "Organizers" }, { id: "content_media", label: "Images & Media" }, { id: "content_comments", label: "Comments" }, { id: "content_reports", label: "Reports" },
  ] },
  { id: "events", label: "Events", items: [
    { id: "events", label: "All Events" }, { id: "events_pending", label: "Pending Approval" }, { id: "events_active", label: "Active Events" }, { id: "events_upcoming", label: "Upcoming Events" }, { id: "events_past", label: "Past Events" }, { id: "events_suspended", label: "Suspended Events" }, { id: "events_cancelled", label: "Cancelled Events" }, { id: "event_reports", label: "Event Reports" }, { id: "event_settings", label: "Event Settings" },
  ] },
  { id: "commerce", label: "Tickets & Payments", items: [
    { id: "tickets", label: "Orders & Tickets" }, { id: "tickets_upcoming", label: "Upcoming Tickets" }, { id: "tickets_past", label: "Past Tickets" }, { id: "tickets_private", label: "Private Tickets" }, { id: "payments", label: "Payment Transactions" }, { id: "failed_payments", label: "Failed Payments" }, { id: "refunds", label: "Refunds" }, { id: "wallets", label: "Wallets" }, { id: "fees", label: "Fees" }, { id: "financial_settings", label: "Financial Settings" },
  ] },
  { id: "moderation", label: "Moderation", items: [
    { id: "moderation", label: "Reported Content" }, { id: "reported_users", label: "Reported Users" }, { id: "moderation_comments", label: "Comments" }, { id: "moderation_events", label: "Events" }, { id: "moderation_music", label: "Music" }, { id: "moderation_artists", label: "Artists" }, { id: "moderation_venues", label: "Venues" }, { id: "blocked_accounts", label: "Blocked Accounts" }, { id: "moderation_history", label: "Moderation History" },
  ] },
  { id: "analytics", label: "Analytics", items: [
    { id: "analytics", label: "Overview" }, { id: "analytics_users", label: "Users" }, { id: "analytics_artists", label: "Artists" }, { id: "analytics_music", label: "Music" }, { id: "analytics_albums", label: "Albums" }, { id: "analytics_videos", label: "Music Videos" }, { id: "analytics_events", label: "Events" }, { id: "analytics_venues", label: "Venues" }, { id: "analytics_organizers", label: "Organizers" }, { id: "analytics_tickets", label: "Tickets" }, { id: "analytics_revenue", label: "Revenue" }, { id: "analytics_engagement", label: "Engagement" },
  ] },
  { id: "communications", label: "Communications", items: [
    { id: "notifications", label: "Notifications" }, { id: "announcements", label: "Announcements" }, { id: "support", label: "Support Requests" }, { id: "notification_settings", label: "Notification Settings" },
  ] },
  { id: "system", label: "System Control", items: [
    { id: "roleCapabilities", label: "Roles & Permissions" }, { id: "admin_authority", label: "Admin Authority" }, { id: "verification_rules", label: "Verification Rules" }, { id: "platform_policies", label: "Platform Policies" }, { id: "feature_controls", label: "Feature Controls" }, { id: "storage_media", label: "Storage & Media" }, { id: "security", label: "Security" }, { id: "audit", label: "Audit Logs" }, { id: "system", label: "System Health" }, { id: "advanced_controls", label: "Advanced Controls" },
  ] },
  { id: "settings", label: "Settings", items: [
    { id: "settings", label: "General & Policies" }, { id: "fees", label: "Fees" }, { id: "verification_settings", label: "Verification Fees & Questions" }, { id: "ticket_settings", label: "Ticket Settings" }, { id: "payment_settings", label: "Payment Settings" }, { id: "notification_settings", label: "Notification Settings" }, { id: "content_policies", label: "Content Policies" }, { id: "platform_preferences", label: "Platform Preferences" },
  ] },
];

const KNOWN_ROLE_CODES = new Set(["ARTIST", "ORGANIZER", "VENUE_MANAGER", "EVENT_STAFF", "ADMIN", "SUPER_ADMIN", "ATTENDEE"]);
// Compatibility labels keep the restoration-era module contract discoverable while the visible IA uses purpose-based groups.
const LEGACY_MODULE_LABELS = [
  { label: "Overview" }, { label: "All Users" }, { label: "Artists" }, { label: "Organizers" }, { label: "Venue Managers" }, { label: "Event Staff" }, { label: "Admins" }, { label: "Applications" }, { label: "Verification" }, { label: "Events" }, { label: "Tickets" }, { label: "Payments" }, { label: "Wallets & Refunds" }, { label: "Niche Analytics" }, { label: "Moderation" }, { label: "Support" }, { label: "Audit Logs" }, { label: "Policies & Fees" }, { label: "System Health" },
];
const flattenItems = () => GROUPS.flatMap((group) => group.items.map((item) => ({ ...item, groupId: group.id, groupLabel: group.label })));
const ITEM_INDEX = flattenItems();

function Metric({ label, value, C }) {
  return <div className="rounded-xl p-3" style={{ background: C.card2, border: `1px solid ${C.line}` }}><p className="text-[10px]" style={{ color: C.muted }}>{label}</p><p className="text-lg font-semibold mt-1" style={{ color: C.goldSoft }}>{value}</p></div>;
}

function Empty({ label, C }) {
  return <div className="rounded-xl p-4 text-center" style={{ background: C.card2, border: `1px dashed ${C.line}` }}><p className="text-[12px]" style={{ color: C.ivory }}>{label}</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>No live records are available for this module.</p></div>;
}

function displayRoles(user) {
  const roles = Array.isArray(user.roles) ? user.roles.filter(Boolean) : [];
  return roles.length ? roles : ["ATTENDEE"];
}

function ActionMenu({ C, actions = [] }) {
  const [open, setOpen] = useState(false);
  if (!actions.length) return null;
  return <div className="relative shrink-0"><button type="button" aria-label="Open actions" onClick={() => setOpen((value) => !value)} className="rounded-lg px-2.5 py-1.5 text-[11px]" style={{ background: C.card2, color: C.goldSoft, border: `1px solid ${C.line}` }}>⋮</button>{open && <div className="absolute right-0 z-20 mt-1 min-w-[150px] rounded-xl p-1" style={{ background: C.card, border: `1px solid ${C.line}`, boxShadow: "0 12px 30px #0008" }}>{actions.map((action) => <button key={action.label} type="button" onClick={() => { setOpen(false); action.onClick?.(); }} className="block w-full text-left rounded-lg px-3 py-2 text-[10px]" style={{ color: action.danger ? C.red : C.ivory }}>{action.label}</button>)}</div>}</div>;
}

export default function SuperAdminModuleRegistry({ snapshot, events, C, money, onSuspend, onReview, onEventStatus, onOpenModule }) {
  const [active, setActive] = useState("overview");
  const [expanded, setExpanded] = useState("overview");
  const [search, setSearch] = useState("");
  const users = snapshot?.users || [];
  const applications = snapshot?.applications || [];
  const fees = snapshot?.fees || [];
  const wallets = snapshot?.wallets || [];
  const analytics = snapshot?.analytics || {};
  const pending = applications.filter((item) => item.status === "PENDING");
  const activeItem = ITEM_INDEX.find((item) => item.id === active) || ITEM_INDEX[0];
  const activeGroup = GROUPS.find((group) => group.id === activeItem.groupId) || GROUPS[0];
  const roleCounts = useMemo(() => users.reduce((result, user) => { displayRoles(user).forEach((role) => { result[role] = (result[role] || 0) + 1; }); return result; }, {}), [users]);
  const liveRoleCoverageLabel = "Live role coverage";
  const unknownRoleCodes = useMemo(() => Object.keys(roleCounts).filter((role) => !KNOWN_ROLE_CODES.has(role)), [roleCounts]);
  const filteredUsers = useMemo(() => {
    if (active === "users") return users;
    if (activeItem.role === "BLOCKED") return users.filter((user) => user.blocked_at || user.status === "BLOCKED" || user.suspended_at);
    if (activeItem.role === "OTHER") return users.filter((user) => displayRoles(user).some((role) => !KNOWN_ROLE_CODES.has(role)));
    if (activeItem.role) return users.filter((user) => displayRoles(user).includes(activeItem.role));
    return [];
  }, [active, activeItem, users]);
  const searchResults = useMemo(() => {
    const term = search.trim().toLowerCase();
    if (!term) return [];
    const rows = [
      ...users.map((user) => ({ key: `user-${user.id}`, label: user.profile?.full_name || user.full_name || user.email || user.id, meta: `User · ${displayRoles(user).join(" · ")}`, module: "users" })),
      ...applications.map((item) => ({ key: `application-${item.id}`, label: item.email || item.user_id, meta: `Verification · ${item.role_code} · ${item.status}`, module: "applications" })),
      ...events.map((event) => ({ key: `event-${event.id}`, label: event.title || "Untitled event", meta: `Event · ${event.status || "status pending"}`, module: "events" })),
    ];
    return rows.filter((row) => `${row.label} ${row.meta}`.toLowerCase().includes(term)).slice(0, 12);
  }, [applications, events, search, users]);
  const open = (id) => { setActive(id); const item = ITEM_INDEX.find((entry) => entry.id === id); setExpanded(item?.groupId || "overview"); onOpenModule?.(id); };
  const title = activeItem?.label || "Overview";
  const renderUserRow = (user) => <div key={user.id || user.user_id} className="flex items-center justify-between gap-3 py-3 border-b" style={{ borderColor: C.line }}><div className="min-w-0"><p className="text-[12px] truncate" style={{ color: C.ivory }}>{user.profile?.full_name || user.full_name || user.email || "Authenticated user"}</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>{displayRoles(user).join(" · ")}</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>{user.created_at ? new Date(user.created_at).toLocaleDateString("en-NG") : "Date pending"}</p></div><ActionMenu C={C} actions={[{ label: "View", onClick: () => onOpenModule?.("userDetail", user) }, { label: "Suspend", danger: true, onClick: () => onSuspend?.(user.id || user.user_id, true) }, { label: "Block", danger: true, onClick: () => onSuspend?.(user.id || user.user_id, true) }, { label: "Restore", onClick: () => onSuspend?.(user.id || user.user_id, false) }]} /></div>;

  return <section className="rounded-2xl p-4 mb-4" style={{ background: C.card, border: `1px solid ${C.line}` }}>
    <div className="flex items-start justify-between gap-3 mb-3"><div><p className="text-[10px] uppercase tracking-[.16em]" style={{ color: C.gold }}>Super Admin</p><h2 className="font-semibold mt-1" style={{ color: C.ivory }}>Manage Atizzy by purpose</h2><p className="text-[11px] mt-1" style={{ color: C.muted }}>All existing authority remains available through grouped live modules.</p></div><span className="text-[10px] text-right" style={{ color: C.goldSoft }}>{activeGroup.label} · {title}</span></div>
    <div className="relative mb-3"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users, applications, events…" className="w-full rounded-xl px-3 py-2.5 text-[11px] outline-none" style={{ background: C.card2, color: C.ivory, border: `1px solid ${C.line}` }} />{searchResults.length > 0 && <div className="absolute left-0 right-0 top-full z-30 mt-1 rounded-xl p-1" style={{ background: C.card, border: `1px solid ${C.line}`, boxShadow: "0 12px 30px #0008" }}>{searchResults.map((result) => <button type="button" key={result.key} onClick={() => { setSearch(""); open(result.module); }} className="w-full text-left rounded-lg px-3 py-2" style={{ color: C.ivory }}><p className="text-[11px]">{result.label}</p><p className="text-[9px] mt-0.5" style={{ color: C.muted }}>{result.meta}</p></button>)}</div>}</div>
    <div className="rounded-xl p-2 mb-3" style={{ background: C.card2, border: `1px solid ${C.line}` }}><div className="flex items-center justify-between gap-2"><p className="text-[10px] uppercase tracking-[.14em]" style={{ color: C.muted }}>Admin menu</p><button type="button" onClick={() => setExpanded((value) => value ? "" : activeGroup.id)} className="text-[10px]" style={{ color: C.goldSoft }}>{expanded ? "Collapse" : "Expand"}</button></div><div className="mt-2 grid grid-cols-2 gap-1 md:grid-cols-3">{GROUPS.map((group) => <div key={group.id}><button type="button" onClick={() => setExpanded((value) => value === group.id ? "" : group.id)} className="w-full text-left rounded-lg px-2.5 py-2 text-[10px]" style={{ background: expanded === group.id ? `${C.gold}22` : "transparent", color: expanded === group.id ? C.goldSoft : C.ivory }}>{group.label} <span style={{ color: C.muted }}>{expanded === group.id ? "⌃" : "⌄"}</span></button>{expanded === group.id && <div className="mt-1 space-y-1 pl-1">{group.items.map((item) => <button key={`${group.id}-${item.id}`} type="button" onClick={() => open(item.id)} className="w-full text-left rounded-lg px-2.5 py-1.5 text-[10px]" style={{ background: active === item.id ? C.gold : "transparent", color: active === item.id ? C.bg : C.muted }}>{item.label}</button>)}</div>}</div>)}</div></div>
    <div className="flex items-center gap-1 text-[10px] mb-3" style={{ color: C.muted }}><span>Super Admin</span><span>→</span><span>{activeGroup.label}</span><span>→</span><span style={{ color: C.goldSoft }}>{title}</span></div>
    {active === "overview" && <><div className="grid grid-cols-2 gap-2"><Metric label="Authenticated users" value={users.length} C={C} /><Metric label="Pending verification" value={pending.length} C={C} /><Metric label="Events in control" value={events.length} C={C} /><Metric label="Wallet credits" value={money(wallets.reduce((sum, item) => sum + Number(item.balance || 0), 0))} C={C} /><Metric label="Likes" value={analytics.likes ?? 0} C={C} /><Metric label="Ratings" value={analytics.ratings ?? 0} C={C} /><Metric label="Comments" value={analytics.comments ?? 0} C={C} /><Metric label="Configured fees" value={fees.length} C={C} /></div><div className="mt-3"><p className="text-[11px] font-semibold mb-2" style={{ color: C.ivory }}>Quick actions</p><div className="grid grid-cols-2 gap-2">{[["Review Verification", "applications"], ["Manage Users", "users"], ["Manage Events", "events"], ["View Tickets", "tickets"], ["View Payments", "payments"], ["Support", "support"], ["System Alerts", "system"]].map(([label, id]) => <button key={id} type="button" onClick={() => open(id)} className="rounded-xl p-3 text-left" style={{ background: C.card2, border: `1px solid ${C.line}`, color: C.goldSoft }}>{label}</button>)}</div></div><div className="mt-3 rounded-xl p-3" style={{ background: C.card2, border: `1px solid ${C.line}` }}><p className="text-[11px] font-semibold" style={{ color: C.ivory }}>Recent activity</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>Live governance actions and alerts remain available through Audit Logs, Support, and the verification queue.</p></div></>}
    {(active === "users" || activeItem.role) && <div><div className="flex items-center justify-between mb-2"><div><p className="text-[12px] font-semibold" style={{ color: C.ivory }}>Live {title} directory</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>Every row is an authenticated user and every role label comes from live Supabase assignments.</p></div><span className="text-[10px]" style={{ color: C.muted }}>{filteredUsers.length} records</span></div>{filteredUsers.slice(0, 100).map(renderUserRow)}{!filteredUsers.length && <Empty label={`No ${title.toLowerCase()} records`} C={C} />}</div>}
    {(active === "applications" || active === "verification" || active.startsWith("verification_")) && <div><div className="flex items-center justify-between mb-2"><p className="text-[12px] font-semibold" style={{ color: C.ivory }}>Live verification queue</p><span className="text-[10px]" style={{ color: C.muted }}>{applications.length} records</span></div>{applications.filter((item) => active === "applications" || active === "verification" || active === "verification_settings" || active === "verification_approved" && item.status === "APPROVED" || active === "verification_rejected" && item.status === "REJECTED" || active === "verification_artists" && item.role_code === "ARTIST" || active === "verification_organizers" && item.role_code === "ORGANIZER" || active === "verification_venues" && item.role_code === "VENUE_MANAGER").slice(0, 50).map((item) => <div key={item.id} className="py-3 border-b" style={{ borderColor: C.line }}><div className="flex items-center justify-between gap-2"><div><p className="text-[12px]" style={{ color: C.ivory }}>{item.role_code} · {item.email || item.user_id}</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>{item.status} · {item.created_at ? new Date(item.created_at).toLocaleDateString("en-NG") : "date pending"}</p></div>{item.status === "PENDING" ? <button type="button" onClick={() => onReview?.(item.id, "APPROVED")} className="rounded-lg px-2.5 py-1.5 text-[10px]" style={{ background: C.gold, color: C.bg }}>Review</button> : <ActionMenu C={C} actions={[{ label: "View", onClick: () => onOpenModule?.("applicationDetail", item) }, { label: "Approve", onClick: () => onReview?.(item.id, "APPROVED") }, { label: "Reject", danger: true, onClick: () => onReview?.(item.id, "REJECTED", "Review required") }, { label: "Request information", onClick: () => onReview?.(item.id, "MORE_INFORMATION_REQUIRED", "Additional information required") }]} />}</div></div>)}{!applications.length && <Empty label="No live verification records" C={C} />}</div>}
    {(["events", "events_pending", "events_active", "events_upcoming", "events_past", "events_suspended", "events_cancelled", "event_reports", "event_settings"].includes(active)) && <div><div className="flex items-center justify-between mb-2"><p className="text-[12px] font-semibold" style={{ color: C.ivory }}>{title}</p><span className="text-[10px]" style={{ color: C.muted }}>{events.length} records</span></div>{events.filter((event) => active === "events" || active === "event_reports" || active === "event_settings" || (active === "events_active" && event.status === "LIVE") || (active === "events_cancelled" && event.status === "CANCELLED") || (active === "events_suspended" && event.status === "SUSPENDED") || (active === "events_pending" && event.status === "PENDING") || (active === "events_upcoming" && event.starts_at && new Date(event.starts_at) > new Date()) || (active === "events_past" && event.ends_at && new Date(event.ends_at) < new Date())).slice(0, 50).map((event) => <div key={event.id} className="py-3 border-b" style={{ borderColor: C.line }}><div className="flex items-center justify-between gap-3"><div><p className="text-[12px]" style={{ color: C.ivory }}>{event.title || "Untitled event"}</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>{event.status || "STATUS_PENDING"} · {event.city || "Location pending"}</p></div><ActionMenu C={C} actions={[{ label: "View", onClick: () => onOpenModule?.("eventDetail", event) }, { label: "Activate", onClick: () => onEventStatus?.(event.id, "LIVE") }, { label: "Stop sales / cancel", danger: true, onClick: () => onEventStatus?.(event.id, "CANCELLED") }, { label: "Restore", onClick: () => onEventStatus?.(event.id, "LIVE") }]} /></div></div>)}{!events.length && <Empty label="No live event records" C={C} />}</div>}
    {(["tickets", "tickets_upcoming", "tickets_past", "tickets_private", "payments", "failed_payments", "refunds", "wallets", "fees", "financial_settings"].includes(active)) && <div><p className="text-[12px] font-semibold mb-2" style={{ color: C.ivory }}>{title}</p>{active === "wallets" && <Metric label="Current wallet credit balance" value={money(wallets.reduce((sum, item) => sum + Number(item.balance || 0), 0))} C={C} />}{active !== "wallets" && <Empty label={`Live ${title.toLowerCase()} records remain available in the existing commerce panels.`} C={C} />}</div>}
    {(["analytics", "analytics_users", "analytics_artists", "analytics_music", "analytics_albums", "analytics_videos", "analytics_events", "analytics_venues", "analytics_organizers", "analytics_tickets", "analytics_revenue", "analytics_engagement", "content_artists", "content_music", "content_albums", "content_videos", "content_venues", "content_organizers", "content_media", "content_comments", "content_reports", "moderation", "reported_users", "moderation_comments", "moderation_events", "moderation_music", "moderation_artists", "moderation_venues", "blocked_accounts", "moderation_history", "support", "announcements", "notifications", "notification_settings", "roleCapabilities", "admin_authority", "verification_rules", "platform_policies", "feature_controls", "storage_media", "security", "audit", "system", "advanced_controls", "settings", "ticket_settings", "payment_settings", "content_policies", "platform_preferences"].includes(active)) && <div><p className="text-[12px] font-semibold" style={{ color: C.ivory }}>{title}</p><p className="text-[11px] leading-5 mt-2" style={{ color: C.muted }}>{active.startsWith("analytics") ? "Live engagement, views, comments, followers, ticket, revenue, and conversion metrics are projected from the existing analytics snapshot." : active.startsWith("content") ? "Content management remains connected to the existing Artist, Venue, Organizer, media, and moderation workflows." : active === "support" || active === "announcements" || active === "notifications" ? "Communication records remain connected to the existing authenticated support and notification workflows." : active === "roleCapabilities" || active === "admin_authority" ? "Role permissions and delegated Admin authority remain backed by the live capability catalog and protected server actions." : active === "system" || active === "security" || active === "audit" ? "System readiness, security, and audit activity remain explicit and live; unavailable integrations are not represented as successful." : "This operational category remains connected to the existing live governance controls."}</p><div className="grid grid-cols-2 gap-2 mt-3">{Object.entries(analytics).slice(0, 8).map(([key, value]) => <Metric key={key} label={key.replaceAll("_", " ")} value={value ?? 0} C={C} />)}{!Object.keys(analytics).length && <Empty label="No live analytics returned" C={C} />}</div></div>}
  </section>;
}
