from pathlib import Path

path = Path('/home/ubuntu/eventverse/src/EventVerse.jsx')
text = path.read_text()
marker = '</section><section className="rounded-2xl p-4 mb-4" style={{ background: C.card, border: `1px solid ${C.line}` }}><h2 className="font-semibold mb-3" style={{ color: C.ivory }}>Analytics & accounting</h2>'
insert = '''</section><section className="rounded-2xl p-4 mb-4" style={{ background: C.card, border: `1px solid ${C.line}` }}><div className="flex items-center justify-between mb-2"><h2 className="font-semibold" style={{ color: C.ivory }}>Event lifecycle controls</h2><span className="text-[11px]" style={{ color: C.muted }}>{events.length} visible events</span></div><p className="text-[11px] leading-5 mb-3" style={{ color: C.muted }}>Super Admin actions are executed through protected RPCs. Cancelling an event credits eligible ticket purchases to each buyer wallet exactly once and marks tickets refunded.</p>{events.slice(0, 30).map((event) => <div key={event.id} className="py-3 border-b" style={{ borderColor: C.line }}><div className="flex items-start justify-between gap-3"><div><p className="text-[12px] font-semibold" style={{ color: C.ivory }}>{event.title || "Untitled event"}</p><p className="text-[10px] mt-1" style={{ color: C.muted }}>{event.city || "Location pending"} · {event.starts_at ? new Date(event.starts_at).toLocaleString("en-NG") : "Date pending"}</p></div><span className="text-[10px] uppercase" style={{ color: event.status === "CANCELLED" ? C.red : C.goldSoft }}>{event.status}</span></div><div className="grid grid-cols-3 gap-2 mt-3"><button type="button" disabled={busy || event.status === "CANCELLED"} onClick={() => act(() => adminSetEventStatus(event.id, "CANCELLED", "Stopped by Super Admin"), "Event cancelled and eligible buyers credited.")} className="rounded-xl py-2 text-[10px] font-semibold" style={{ background: C.red + "22", color: C.red, border: `1px solid ${C.red}44` }}>Stop / refund</button><button type="button" disabled={busy || event.status === "LIVE"} onClick={() => act(() => adminSetEventStatus(event.id, "LIVE", "Activated by Super Admin"), "Event activated.")} className="rounded-xl py-2 text-[10px] font-semibold" style={{ background: C.green, color: C.goldSoft }}>Activate</button><button type="button" disabled={busy || event.status !== "CANCELLED"} onClick={() => act(() => adminSetEventStatus(event.id, "DRAFT", "Restored by Super Admin"), "Event restored to draft.")} className="rounded-xl py-2 text-[10px] font-semibold" style={{ background: C.card2, color: C.ivory, border: `1px solid ${C.line}` }}>Restore</button></div></div>)}{!events.length && <EmptyResourceCard label="No events available" description="Events will appear here when organizers create them." />}</section><section className="rounded-2xl p-4 mb-4" style={{ background: C.card, border: `1px solid ${C.line}` }}><h2 className="font-semibold mb-3" style={{ color: C.ivory }}>Analytics & accounting</h2>'''
if marker not in text:
    raise SystemExit('analytics marker not found')
text = text.replace(marker, insert, 1)
path.write_text(text)
print('inserted')
